dashboard/nav: store expand states in cookie
liqd/adhocracy-plus pull request #1472
Opened 2021-09-29 15:52 UTC by khamui

2021-09-30 14:24 UTC, phillimorland requested changes
Yo I would just change spelling and let me know what you think about the load. 
Also I just noticed that there is this error in console 
`Uncaught Error: Syntax error, unrecognized expression: ##dashboardCollapseProj`
do you get that?

2021-09-30 14:24 UTC, phillimorland commented on adhocracy-plus/assets/js/app.js
> +import { initDashboardAccordeon } from '../../../apps/dashboard/helpers'
Accordeon is spelt Accordion, sorry! I think it's also probably wrong in mB but just for code searches it's better to have it correct

2021-09-30 14:24 UTC, phillimorland commented on adhocracy-plus/assets/js/app.js
>  }
I think it might be better to only load this on dashboard as it's not needed anywhere else, what do you think?

2021-10-04 09:19 UTC, khamui commented on adhocracy-plus/assets/js/init_dashboard_accordion.js
> +document.addEventListener('DOMContentLoaded', initDashboardAccordion, false)
this is added because otherwise it will fire the function too early.

2021-10-04 15:28 UTC, phillimorland commented
> Yo I would just change spelling and let me know what you think about the load. Also I just noticed that there is this error in console `Uncaught Error: Syntax error, unrecognized expression: ##dashboardCollapseProj` do you get that? works beautifully though! :)

still getting that error in console? i assume it's the double hash but notsure where/why? it's working so also fine to merge but would be nice to not have additional console errros for release as we already have too many :( @khamui

2021-10-04 15:29 UTC, phillimorland reviewed
if console error isn't easy fix then merge as it's all there and is great!

2021-10-05 07:58 UTC, khamui commented
> > Yo I would just change spelling and let me know what you think about the load. Also I just noticed that there is this error in console `Uncaught Error: Syntax error, unrecognized expression: ##dashboardCollapseProj` do you get that? works beautifully though! :)
> 
> still getting that error in console? i assume it's the double hash but notsure where/why? it's working so also fine to merge but would be nice to not have additional console errros for release as we already have too many :( @khamui

ah sorry i didn't reply to this. but I tested on my side and i don't get this error. Anything special you did to trigger it?

2021-10-05 08:13 UTC, merged