projects/serializers: sending project.information html formatted
liqd/adhocracy-plus pull request #1953
Opened 2022-06-28 13:41 UTC by khamui

2022-07-12 10:58 UTC, goapunk requested changes
the serializer tests now fail and need fixing.

2022-07-13 07:22 UTC, fuzzylogic2000 reviewed
Nice! Could you now also squash the commits? (When you just do a fixup with the second one, you will not have the weird commit message with "squash" in it.)

2022-07-13 07:22 UTC, fuzzylogic2000 commented on tests/projects/test_app_project_api.py
> +    html_string = '<p>text with a <strong>bold</strong> bit</p>'
Even though, we do not remove the tags anymore, you could test that the strip works and removes whitespace.

2022-07-13 14:51 UTC, khamui commented
@fuzzylogic2000 oh makes sense. Now it tests the strip of whitespaces

2022-07-13 15:23 UTC, merged