WIP [Issues] templates/*: improve semantic html and add missing heading headings f…
liqd/adhocracy-plus pull request #2169
Opened 2022-12-20 14:45 UTC by phillimorland

…ixes #1870 also fixes some a11y for the new tiles

2022-12-20 15:50 UTC, phillimorland commented
@fuzzylogic2000 there's some weird stuff going on with the abbreviated times but when looking at it I didn't understand the different indexes when referencing the same time?! maybe we can look at it together or you can add a comment explanation?

2022-12-21 08:52 UTC, fuzzylogic2000 requested changes
Looks good! Only one typo that needs to be fixed first.
I will add an explanation for the ebbreviated stuff and the blocktranslate in an extra branch.

2022-12-21 08:52 UTC, fuzzylogic2000 commented on apps/projects/templates/a4_candy_projects/includes/project_timeline-carousel.html
> +                                    <date>{% trans 'from' %} {{ date.date | date }}</date>
Not new, but seeing this: we should probably use blocktranslate here.

2022-12-21 08:52 UTC, fuzzylogic2000 commented on apps/projects/templates/a4_candy_projects/project_detail.html
> +                    <h2 class="visually-hidden">{% translate 'Online articipation' %}</h2>
There is a p missing here 'Online participation'

2022-12-21 09:56 UTC, fuzzylogic2000 approved these changes
Noice!

2022-12-21 09:56 UTC, merged