update translations
liqd/adhocracy-plus pull request #2518
Opened 2023-08-09 12:32 UTC by goapunk

2023-08-18 10:42 UTC, m4ra requested changes
there is a grammar err.

2023-08-18 10:42 UTC, m4ra commented on locale-source/locale/tr/LC_MESSAGES/djangojs.po
> +msgid "This {}comment{} has been reported 1 time since it's creation"
I think correct grammar is `its creation` or `it's created`. Can you check with @philli-m ?

2023-09-04 17:52 UTC, m4ra approved these changes

2023-09-04 17:55 UTC, m4ra commented
@goapunk aren't we squashing commits into one? Do we need a fix-typo commit separately in the git history? Also @hklarner has a similar commit in his PR.

2023-09-05 07:31 UTC, goapunk commented
> @goapunk aren't we squashing commits into one? Do we need a fix-typo commit separately in the git history? Also @hklarner has a similar commit in his PR.

@m4ra generally (I think) we only squash if commits are part of one (connected) change/feature. But if they are logically separate changes they should have their own commit (and then can also be easily reverted individually if necessary). In this particular case the changes in the second commit are auto-generated by django / transifex, so I wouldn't mix them with my manual changes.

2024-12-09 16:25 UTC, closed without merging